Added function to load users from a config file
ContainerSolutions/trow pull request #182
Opened 2020-10-05 09:53 UTC by Spazzy757

## Changelog

 - Adds a function that will allow users to be loaded from a yaml config file in the following format:

```yaml
users:
- name: "example"
  password: "123456789"
```
This will allow a list of users to given at runtime via a secret to the trow container>
There is still work for this function to be introduced into the main start-up of trow

2020-10-08 12:06 UTC, amouat requested changes
Looks good. I think we should think about refactoring the interface a bit though.

Apologies if I'm saying the opposite of something I said before, which wouldn't surprise me!

2020-10-08 12:06 UTC, amouat commented on src/users.rs
> +            User::load_users_from_file().is_ok(),
I'm tempted to say change this to just:

```
User::load_users_from_file().unwrap();
```
Or `expect` if you want the explicit message. But admittedly using asset does make it clearer what we're testing.

2020-10-08 12:24 UTC, Spazzy757 commented on src/users.rs
> +        let users_file = env::var("USER_CONFIG").unwrap_or("users.yaml".to_string());
Yes exactly, need to intergrate it into the start up of trow and into the auth flow

2021-02-11 13:56 UTC, mathijshoogland commented
@Spazzy757 I'd like to pick this one up and process Adrian's requested changes, maybe schedule a short 1-on-1 with you next week to walk through it all, agree?

2021-02-15 10:55 UTC, Spazzy757 commented
> @Spazzy757 I'd like to pick this one up and process Adrian's requested changes, maybe schedule a short 1-on-1 with you next week to walk through it all, agree?

Sure no problem This PR is quite old now, it would possibly take a lot more work

2022-10-14 08:30 UTC, closed without merging