Refacort kustomize patches for interoperability
ContainerSolutions/trow pull request #185
Opened 2020-10-06 22:20 UTC by blaggacao

non-GVK'ded yaml files break some CM tools such as the very
kustomize/kpt cfg subcommand. Instead of removing the yaml extension,
which might be deceptive, inline the patches.

2020-10-07 16:37 UTC, amouat commented
Ah, excellent. This looks great. Let me test it first, but this should be good to go.

2020-10-09 09:40 UTC, amouat requested changes
All the changes look good, but could you also update the instructions in `INSTALL.md` in line with these changes?

2020-10-09 17:40 UTC, blaggacao commented
@amouat Done. Please review https://github.com/ContainerSolutions/trow/pull/185/commits/6c9151371e7f925b465dcdeca726255cc53fd590

2020-10-13 09:10 UTC, amouat approved these changes

2020-10-13 09:10 UTC, merged

2020-10-13 09:11 UTC, amouat commented
Looks good, thanks.